[package]
name = "rust-web"
version = "0.1.0"
edition = "2018"

[dependencies]
axum = "0.2.8"
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.12.0", features = ["full"] }
tower-http = {version = "0.1.1", features = ["fs"] }

